// Catalogue LPC (auto). Assets CC-BY-SA — voir public/lpc/CREDITS.md.
export type Rarity = "base"|"commun"|"rare"|"epique"|"legendaire"|"mythique";
export const RARITY_COLORS: Record<Rarity,string> = {base:"#9aa7b3",commun:"#9aa7b3",rare:"#4d9bff",epique:"#b06bff",legendaire:"#ffcf4d",mythique:"#ff5d7a"};
export const RARITY_LABEL: Record<Rarity,string> = {base:"Base",commun:"Commun",rare:"Rare",epique:"\u00c9pique",legendaire:"L\u00e9gendaire",mythique:"Mythique"};
export type Slot = "hair"|"torso"|"legs"|"feet"|"headwear";
export const EQUIP_SLOTS: Slot[] = ["headwear","hair","torso","legs","feet"];
export const SLOT_LABEL: Record<Slot,string> = {headwear:"Couvre-chef",hair:"Cheveux",torso:"Torse",legs:"Jambes",feet:"Pieds"};
export type ColorOpt = { name: string; file: string };
export type LpcItem = { key: string; name: string; slot: string; rarity: Rarity; zPos: number; file?: string; colors?: ColorOpt[] };
export const BASE_LAYERS: LpcItem[] = [{key:"body_male",name:"Corps",slot:"body",rarity:"base",zPos:10,file:"/lpc/body/body_male.png"},{key:"head_male",name:"Tête",slot:"head",rarity:"base",zPos:100,file:"/lpc/head/head_male.png"}];
export const ITEMS: LpcItem[] = [
  {key:"feet_boots_basic",name:"Basic Boots",slot:"feet",rarity:"commun",zPos:25,colors:[{name:"black",file:"/lpc/feet/feet_boots_basic__black.png"},{name:"blue",file:"/lpc/feet/feet_boots_basic__blue.png"},{name:"bluegray",file:"/lpc/feet/feet_boots_basic__bluegray.png"},{name:"brass",file:"/lpc/feet/feet_boots_basic__brass.png"},{name:"bronze",file:"/lpc/feet/feet_boots_basic__bronze.png"},{name:"brown",file:"/lpc/feet/feet_boots_basic__brown.png"},{name:"ceramic",file:"/lpc/feet/feet_boots_basic__ceramic.png"},{name:"charcoal",file:"/lpc/feet/feet_boots_basic__charcoal.png"}]},
  {key:"feet_boots_fold",name:"Folded Rim Boots",slot:"feet",rarity:"commun",zPos:25,colors:[{name:"black",file:"/lpc/feet/feet_boots_fold__black.png"},{name:"blue",file:"/lpc/feet/feet_boots_fold__blue.png"},{name:"bluegray",file:"/lpc/feet/feet_boots_fold__bluegray.png"},{name:"brass",file:"/lpc/feet/feet_boots_fold__brass.png"},{name:"bronze",file:"/lpc/feet/feet_boots_fold__bronze.png"},{name:"brown",file:"/lpc/feet/feet_boots_fold__brown.png"},{name:"ceramic",file:"/lpc/feet/feet_boots_fold__ceramic.png"},{name:"charcoal",file:"/lpc/feet/feet_boots_fold__charcoal.png"}]},
  {key:"feet_boots_revised",name:"Revised Boots",slot:"feet",rarity:"commun",zPos:25,colors:[{name:"black",file:"/lpc/feet/feet_boots_revised__black.png"},{name:"blue",file:"/lpc/feet/feet_boots_revised__blue.png"},{name:"bluegray",file:"/lpc/feet/feet_boots_revised__bluegray.png"},{name:"brass",file:"/lpc/feet/feet_boots_revised__brass.png"},{name:"bronze",file:"/lpc/feet/feet_boots_revised__bronze.png"},{name:"brown",file:"/lpc/feet/feet_boots_revised__brown.png"},{name:"ceramic",file:"/lpc/feet/feet_boots_revised__ceramic.png"},{name:"charcoal",file:"/lpc/feet/feet_boots_revised__charcoal.png"}]},
  {key:"feet_boots_rim",name:"Rimmed Boots",slot:"feet",rarity:"commun",zPos:25,colors:[{name:"black",file:"/lpc/feet/feet_boots_rim__black.png"},{name:"blue",file:"/lpc/feet/feet_boots_rim__blue.png"},{name:"bluegray",file:"/lpc/feet/feet_boots_rim__bluegray.png"},{name:"brass",file:"/lpc/feet/feet_boots_rim__brass.png"},{name:"bronze",file:"/lpc/feet/feet_boots_rim__bronze.png"},{name:"brown",file:"/lpc/feet/feet_boots_rim__brown.png"},{name:"ceramic",file:"/lpc/feet/feet_boots_rim__ceramic.png"},{name:"charcoal",file:"/lpc/feet/feet_boots_rim__charcoal.png"}]},
  {key:"feet_shoes_basic",name:"Basic Shoes",slot:"feet",rarity:"commun",zPos:15,colors:[{name:"black",file:"/lpc/feet/feet_shoes_basic__black.png"},{name:"blue",file:"/lpc/feet/feet_shoes_basic__blue.png"},{name:"bluegray",file:"/lpc/feet/feet_shoes_basic__bluegray.png"},{name:"brass",file:"/lpc/feet/feet_shoes_basic__brass.png"},{name:"bronze",file:"/lpc/feet/feet_shoes_basic__bronze.png"},{name:"brown",file:"/lpc/feet/feet_shoes_basic__brown.png"},{name:"ceramic",file:"/lpc/feet/feet_shoes_basic__ceramic.png"},{name:"charcoal",file:"/lpc/feet/feet_shoes_basic__charcoal.png"}]},
  {key:"feet_shoes_ghillies",name:"Ghillies",slot:"feet",rarity:"commun",zPos:15,colors:[{name:"black",file:"/lpc/feet/feet_shoes_ghillies__black.png"},{name:"blue",file:"/lpc/feet/feet_shoes_ghillies__blue.png"},{name:"bluegray",file:"/lpc/feet/feet_shoes_ghillies__bluegray.png"},{name:"brass",file:"/lpc/feet/feet_shoes_ghillies__brass.png"},{name:"bronze",file:"/lpc/feet/feet_shoes_ghillies__bronze.png"},{name:"brown",file:"/lpc/feet/feet_shoes_ghillies__brown.png"},{name:"ceramic",file:"/lpc/feet/feet_shoes_ghillies__ceramic.png"},{name:"charcoal",file:"/lpc/feet/feet_shoes_ghillies__charcoal.png"}]},
  {key:"feet_shoes_revised",name:"Revised Shoes",slot:"feet",rarity:"commun",zPos:15,colors:[{name:"black",file:"/lpc/feet/feet_shoes_revised__black.png"},{name:"blue",file:"/lpc/feet/feet_shoes_revised__blue.png"},{name:"bluegray",file:"/lpc/feet/feet_shoes_revised__bluegray.png"},{name:"brass",file:"/lpc/feet/feet_shoes_revised__brass.png"},{name:"bronze",file:"/lpc/feet/feet_shoes_revised__bronze.png"},{name:"brown",file:"/lpc/feet/feet_shoes_revised__brown.png"},{name:"ceramic",file:"/lpc/feet/feet_shoes_revised__ceramic.png"},{name:"charcoal",file:"/lpc/feet/feet_shoes_revised__charcoal.png"}]},
  {key:"feet_shoes_sara",name:"Sara Shoes",slot:"feet",rarity:"commun",zPos:15,colors:[{name:"black",file:"/lpc/feet/feet_shoes_sara__black.png"},{name:"blue",file:"/lpc/feet/feet_shoes_sara__blue.png"},{name:"bluegray",file:"/lpc/feet/feet_shoes_sara__bluegray.png"},{name:"brass",file:"/lpc/feet/feet_shoes_sara__brass.png"},{name:"bronze",file:"/lpc/feet/feet_shoes_sara__bronze.png"},{name:"brown",file:"/lpc/feet/feet_shoes_sara__brown.png"},{name:"ceramic",file:"/lpc/feet/feet_shoes_sara__ceramic.png"},{name:"charcoal",file:"/lpc/feet/feet_shoes_sara__charcoal.png"}]},
  {key:"hair_bangs",name:"Bangs",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_bangs.png"},
  {key:"hair_bangslong",name:"Bangslong",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_bangslong.png"},
  {key:"hair_bangslong2",name:"Bangslong2",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_bangslong2.png"},
  {key:"hair_bangsshort",name:"Bangsshort",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_bangsshort.png"},
  {key:"hair_bedhead",name:"Bedhead",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_bedhead.png"},
  {key:"hair_cowlick",name:"Cowlick",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_cowlick.png"},
  {key:"hair_cowlick_tall",name:"Cowlick tall",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_cowlick_tall.png"},
  {key:"hair_curtains",name:"Curtains",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_curtains.png"},
  {key:"hair_curtains_long",name:"Curtains long",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_curtains_long.png"},
  {key:"hair_long",name:"Long",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_long.png"},
  {key:"hair_long_center_part",name:"Long center part",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_long_center_part.png"},
  {key:"hair_long_messy",name:"Long messy",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_long_messy.png"},
  {key:"hair_long_messy2",name:"Long messy2",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_long_messy2.png"},
  {key:"hair_long_straight",name:"Long straight",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_long_straight.png"},
  {key:"hair_loose",name:"Loose",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_loose.png"},
  {key:"hair_wavy",name:"Wavy",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_wavy.png"},
  {key:"headwear_hat_helmet_armet",name:"Armet",slot:"headwear",rarity:"epique",zPos:130,file:"/lpc/headwear/headwear_hat_helmet_armet.png"},
  {key:"headwear_hat_helmet_armet_simple",name:"Simple Armet",slot:"headwear",rarity:"epique",zPos:130,file:"/lpc/headwear/headwear_hat_helmet_armet_simple.png"},
  {key:"headwear_hat_helmet_barbarian",name:"Barbarian",slot:"headwear",rarity:"epique",zPos:130,file:"/lpc/headwear/headwear_hat_helmet_barbarian.png"},
  {key:"headwear_hat_helmet_barbarian_nasal",name:"Barbarian nasal",slot:"headwear",rarity:"epique",zPos:130,file:"/lpc/headwear/headwear_hat_helmet_barbarian_nasal.png"},
  {key:"headwear_hat_helmet_barbarian_viking",name:"Barbarian Viking",slot:"headwear",rarity:"epique",zPos:130,file:"/lpc/headwear/headwear_hat_helmet_barbarian_viking.png"},
  {key:"headwear_hat_helmet_barbuta",name:"Barbuta",slot:"headwear",rarity:"epique",zPos:130,file:"/lpc/headwear/headwear_hat_helmet_barbuta.png"},
  {key:"legs_cuffed",name:"Cuffed Pants",slot:"legs",rarity:"commun",zPos:20,colors:[{name:"black",file:"/lpc/legs/legs_cuffed__black.png"},{name:"blue",file:"/lpc/legs/legs_cuffed__blue.png"},{name:"bluegray",file:"/lpc/legs/legs_cuffed__bluegray.png"},{name:"brown",file:"/lpc/legs/legs_cuffed__brown.png"},{name:"charcoal",file:"/lpc/legs/legs_cuffed__charcoal.png"},{name:"forest",file:"/lpc/legs/legs_cuffed__forest.png"},{name:"gray",file:"/lpc/legs/legs_cuffed__gray.png"},{name:"green",file:"/lpc/legs/legs_cuffed__green.png"}]},
  {key:"legs_formal",name:"Formal Pants",slot:"legs",rarity:"commun",zPos:20,colors:[{name:"base",file:"/lpc/legs/legs_formal__base.png"},{name:"black",file:"/lpc/legs/legs_formal__black.png"},{name:"blue",file:"/lpc/legs/legs_formal__blue.png"},{name:"bluegray",file:"/lpc/legs/legs_formal__bluegray.png"},{name:"brown",file:"/lpc/legs/legs_formal__brown.png"},{name:"charcoal",file:"/lpc/legs/legs_formal__charcoal.png"},{name:"forest",file:"/lpc/legs/legs_formal__forest.png"},{name:"gray",file:"/lpc/legs/legs_formal__gray.png"}]},
  {key:"legs_formal_striped",name:"Striped Formal Pants",slot:"legs",rarity:"commun",zPos:20,colors:[{name:"base",file:"/lpc/legs/legs_formal_striped__base.png"},{name:"black",file:"/lpc/legs/legs_formal_striped__black.png"},{name:"blue",file:"/lpc/legs/legs_formal_striped__blue.png"},{name:"bluegray",file:"/lpc/legs/legs_formal_striped__bluegray.png"},{name:"brown",file:"/lpc/legs/legs_formal_striped__brown.png"},{name:"charcoal",file:"/lpc/legs/legs_formal_striped__charcoal.png"},{name:"forest",file:"/lpc/legs/legs_formal_striped__forest.png"},{name:"gray",file:"/lpc/legs/legs_formal_striped__gray.png"}]},
  {key:"legs_fur",name:"Fur Pants",slot:"legs",rarity:"commun",zPos:20,colors:[{name:"base",file:"/lpc/legs/legs_fur__base.png"},{name:"black",file:"/lpc/legs/legs_fur__black.png"},{name:"blue",file:"/lpc/legs/legs_fur__blue.png"},{name:"bluegray",file:"/lpc/legs/legs_fur__bluegray.png"},{name:"brown",file:"/lpc/legs/legs_fur__brown.png"},{name:"charcoal",file:"/lpc/legs/legs_fur__charcoal.png"},{name:"forest",file:"/lpc/legs/legs_fur__forest.png"},{name:"fur_black",file:"/lpc/legs/legs_fur__fur_black.png"}]},
  {key:"legs_pantaloons",name:"Pantaloons",slot:"legs",rarity:"commun",zPos:20,colors:[{name:"black",file:"/lpc/legs/legs_pantaloons__black.png"},{name:"blue",file:"/lpc/legs/legs_pantaloons__blue.png"},{name:"bluegray",file:"/lpc/legs/legs_pantaloons__bluegray.png"},{name:"brown",file:"/lpc/legs/legs_pantaloons__brown.png"},{name:"charcoal",file:"/lpc/legs/legs_pantaloons__charcoal.png"},{name:"forest",file:"/lpc/legs/legs_pantaloons__forest.png"},{name:"gray",file:"/lpc/legs/legs_pantaloons__gray.png"},{name:"green",file:"/lpc/legs/legs_pantaloons__green.png"}]},
  {key:"legs_pants",name:"Pants",slot:"legs",rarity:"commun",zPos:20,colors:[{name:"black",file:"/lpc/legs/legs_pants__black.png"},{name:"blue",file:"/lpc/legs/legs_pants__blue.png"},{name:"bluegray",file:"/lpc/legs/legs_pants__bluegray.png"},{name:"brown",file:"/lpc/legs/legs_pants__brown.png"},{name:"charcoal",file:"/lpc/legs/legs_pants__charcoal.png"},{name:"forest",file:"/lpc/legs/legs_pants__forest.png"},{name:"gray",file:"/lpc/legs/legs_pants__gray.png"},{name:"green",file:"/lpc/legs/legs_pants__green.png"}]},
  {key:"legs_pants2",name:"Long Pants",slot:"legs",rarity:"commun",zPos:20,colors:[{name:"black",file:"/lpc/legs/legs_pants2__black.png"},{name:"blue",file:"/lpc/legs/legs_pants2__blue.png"},{name:"bluegray",file:"/lpc/legs/legs_pants2__bluegray.png"},{name:"brown",file:"/lpc/legs/legs_pants2__brown.png"},{name:"charcoal",file:"/lpc/legs/legs_pants2__charcoal.png"},{name:"forest",file:"/lpc/legs/legs_pants2__forest.png"},{name:"gray",file:"/lpc/legs/legs_pants2__gray.png"},{name:"green",file:"/lpc/legs/legs_pants2__green.png"}]},
  {key:"legs_widepants",name:"Wide pants",slot:"legs",rarity:"commun",zPos:20,colors:[{name:"black",file:"/lpc/legs/legs_widepants__black.png"},{name:"blue",file:"/lpc/legs/legs_widepants__blue.png"},{name:"bluegray",file:"/lpc/legs/legs_widepants__bluegray.png"},{name:"brown",file:"/lpc/legs/legs_widepants__brown.png"},{name:"charcoal",file:"/lpc/legs/legs_widepants__charcoal.png"},{name:"forest",file:"/lpc/legs/legs_widepants__forest.png"},{name:"gray",file:"/lpc/legs/legs_widepants__gray.png"},{name:"green",file:"/lpc/legs/legs_widepants__green.png"}]},
  {key:"torso_clothes_longsleeve",name:"Longsleeve",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_longsleeve.png"},
  {key:"torso_clothes_longsleeve2",name:"Longsleeve 2",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_longsleeve2.png"},
  {key:"torso_clothes_longsleeve2_buttoned",name:"Longsleeve 2 Buttoned",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_longsleeve2_buttoned.png"},
  {key:"torso_clothes_longsleeve2_cardigan",name:"Cardigan",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_longsleeve2_cardigan.png"},
  {key:"torso_clothes_longsleeve2_polo",name:"Longsleeve Polo",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_longsleeve2_polo.png"},
  {key:"torso_clothes_longsleeve2_scoop",name:"Longsleeve 2 Scoop",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_longsleeve2_scoop.png"},
  {key:"torso_clothes_longsleeve2_vneck",name:"Longsleeve 2 VNeck",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_longsleeve2_vneck.png"},
  {key:"torso_clothes_longsleeve_scoop",name:"Scoop",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_longsleeve_scoop.png"},
  {key:"torso_clothes_longsleeves_cuffed",name:"Cuffed Longsleeves Overlay",slot:"torso",rarity:"commun",zPos:36,file:"/lpc/torso/torso_clothes_longsleeves_cuffed.png"}
];
export const ALL_LAYERS: LpcItem[] = [...BASE_LAYERS, ...ITEMS];
export const ITEM_BY_KEY: Record<string, LpcItem> = Object.fromEntries(ALL_LAYERS.map((i)=>[i.key,i]));
export type EquipSel = { key: string; color?: string };
export type Equipped = Partial<Record<Slot, EquipSel | null>>;
export const DEFAULT_EQUIPPED: Equipped = {"hair": {"key": "hair_bangs"}, "torso": {"key": "torso_clothes_longsleeve"}, "legs": {"key": "legs_cuffed"}, "feet": {"key": "feet_boots_basic"}};
export const STARTER_ITEMS: string[] = ITEMS.map((i)=>i.key);
export function fileFor(item: LpcItem, color?: string | null): string | null {
  if (item.file) return item.file;
  if (item.colors && item.colors.length) {
    if (color) { const f = item.colors.find((c)=>c.name===color); if (f) return f.file; }
    return item.colors[0].file;
  }
  return null;
}
