// Catalogue LPC (auto). Assets CC-BY-SA — public/lpc/CREDITS.md.
export type Rarity = "base"|"commun"|"rare"|"epique"|"legendaire"|"mythique";
export const RARITY_COLORS: Record<Rarity,string> = {base:"#9aa7b3",commun:"#9aa7b3",rare:"#4d9bff",epique:"#b06bff",legendaire:"#ffcf4d",mythique:"#ff5d7a"};
export const RARITY_LABEL: Record<Rarity,string> = {base:"Base",commun:"Commun",rare:"Rare",epique:"\u00c9pique",legendaire:"L\u00e9gendaire",mythique:"Mythique"};
export type Slot = "headwear"|"hair"|"cape"|"torso"|"legs"|"feet";
export const EQUIP_SLOTS: Slot[] = ["headwear","hair","cape","torso","legs","feet"];
export const SLOT_LABEL: Record<Slot,string> = {headwear:"Couvre-chef",hair:"Cheveux",cape:"Cape",torso:"Torse",legs:"Jambes",feet:"Pieds"};
export type ColorOpt = { name: string; file: string };
export type LpcItem = { key: string; name: string; slot: string; rarity: Rarity; zPos: number; file?: string; colors?: ColorOpt[] };
export const BASE_LAYERS: LpcItem[] = [{key:"body_male",name:"Corps",slot:"body",rarity:"base",zPos:10,file:"/lpc/body/body_male.png"},{key:"head_male",name:"T\u00eate",slot:"head",rarity:"base",zPos:100,file:"/lpc/head/head_male.png"}];
export const ITEMS: LpcItem[] = [
  {key:"cape_cape_solid",name:"Solid",slot:"cape",rarity:"rare",zPos:85,file:"/lpc/cape/cape_cape_solid.png"},
  {key:"cape_cape_tattered",name:"Tattered",slot:"cape",rarity:"rare",zPos:85,file:"/lpc/cape/cape_cape_tattered.png"},
  {key:"cape_cape_trim",name:"Cape Trim",slot:"cape",rarity:"rare",zPos:90,file:"/lpc/cape/cape_cape_trim.png"},
  {key:"feet_boots_basic",name:"Basic Boots",slot:"feet",rarity:"rare",zPos:25,colors:[{name:"black",file:"/lpc/feet/feet_boots_basic__black.png"},{name:"blue",file:"/lpc/feet/feet_boots_basic__blue.png"},{name:"bluegray",file:"/lpc/feet/feet_boots_basic__bluegray.png"},{name:"brass",file:"/lpc/feet/feet_boots_basic__brass.png"},{name:"bronze",file:"/lpc/feet/feet_boots_basic__bronze.png"},{name:"brown",file:"/lpc/feet/feet_boots_basic__brown.png"},{name:"ceramic",file:"/lpc/feet/feet_boots_basic__ceramic.png"},{name:"charcoal",file:"/lpc/feet/feet_boots_basic__charcoal.png"},{name:"copper",file:"/lpc/feet/feet_boots_basic__copper.png"},{name:"forest",file:"/lpc/feet/feet_boots_basic__forest.png"}]},
  {key:"feet_boots_fold",name:"Folded Rim Boots",slot:"feet",rarity:"rare",zPos:25,colors:[{name:"black",file:"/lpc/feet/feet_boots_fold__black.png"},{name:"blue",file:"/lpc/feet/feet_boots_fold__blue.png"},{name:"bluegray",file:"/lpc/feet/feet_boots_fold__bluegray.png"},{name:"brass",file:"/lpc/feet/feet_boots_fold__brass.png"},{name:"bronze",file:"/lpc/feet/feet_boots_fold__bronze.png"},{name:"brown",file:"/lpc/feet/feet_boots_fold__brown.png"},{name:"ceramic",file:"/lpc/feet/feet_boots_fold__ceramic.png"},{name:"charcoal",file:"/lpc/feet/feet_boots_fold__charcoal.png"},{name:"copper",file:"/lpc/feet/feet_boots_fold__copper.png"},{name:"forest",file:"/lpc/feet/feet_boots_fold__forest.png"}]},
  {key:"feet_boots_revised",name:"Revised Boots",slot:"feet",rarity:"rare",zPos:25,colors:[{name:"black",file:"/lpc/feet/feet_boots_revised__black.png"},{name:"blue",file:"/lpc/feet/feet_boots_revised__blue.png"},{name:"bluegray",file:"/lpc/feet/feet_boots_revised__bluegray.png"},{name:"brass",file:"/lpc/feet/feet_boots_revised__brass.png"},{name:"bronze",file:"/lpc/feet/feet_boots_revised__bronze.png"},{name:"brown",file:"/lpc/feet/feet_boots_revised__brown.png"},{name:"ceramic",file:"/lpc/feet/feet_boots_revised__ceramic.png"},{name:"charcoal",file:"/lpc/feet/feet_boots_revised__charcoal.png"},{name:"copper",file:"/lpc/feet/feet_boots_revised__copper.png"},{name:"forest",file:"/lpc/feet/feet_boots_revised__forest.png"}]},
  {key:"feet_boots_rim",name:"Rimmed Boots",slot:"feet",rarity:"rare",zPos:25,colors:[{name:"black",file:"/lpc/feet/feet_boots_rim__black.png"},{name:"blue",file:"/lpc/feet/feet_boots_rim__blue.png"},{name:"bluegray",file:"/lpc/feet/feet_boots_rim__bluegray.png"},{name:"brass",file:"/lpc/feet/feet_boots_rim__brass.png"},{name:"bronze",file:"/lpc/feet/feet_boots_rim__bronze.png"},{name:"brown",file:"/lpc/feet/feet_boots_rim__brown.png"},{name:"ceramic",file:"/lpc/feet/feet_boots_rim__ceramic.png"},{name:"charcoal",file:"/lpc/feet/feet_boots_rim__charcoal.png"},{name:"copper",file:"/lpc/feet/feet_boots_rim__copper.png"},{name:"forest",file:"/lpc/feet/feet_boots_rim__forest.png"}]},
  {key:"feet_shoes_basic",name:"Basic Shoes",slot:"feet",rarity:"commun",zPos:15,colors:[{name:"black",file:"/lpc/feet/feet_shoes_basic__black.png"},{name:"blue",file:"/lpc/feet/feet_shoes_basic__blue.png"},{name:"bluegray",file:"/lpc/feet/feet_shoes_basic__bluegray.png"},{name:"brass",file:"/lpc/feet/feet_shoes_basic__brass.png"},{name:"bronze",file:"/lpc/feet/feet_shoes_basic__bronze.png"},{name:"brown",file:"/lpc/feet/feet_shoes_basic__brown.png"},{name:"ceramic",file:"/lpc/feet/feet_shoes_basic__ceramic.png"},{name:"charcoal",file:"/lpc/feet/feet_shoes_basic__charcoal.png"},{name:"copper",file:"/lpc/feet/feet_shoes_basic__copper.png"},{name:"forest",file:"/lpc/feet/feet_shoes_basic__forest.png"}]},
  {key:"feet_shoes_ghillies",name:"Ghillies",slot:"feet",rarity:"commun",zPos:15,colors:[{name:"black",file:"/lpc/feet/feet_shoes_ghillies__black.png"},{name:"blue",file:"/lpc/feet/feet_shoes_ghillies__blue.png"},{name:"bluegray",file:"/lpc/feet/feet_shoes_ghillies__bluegray.png"},{name:"brass",file:"/lpc/feet/feet_shoes_ghillies__brass.png"},{name:"bronze",file:"/lpc/feet/feet_shoes_ghillies__bronze.png"},{name:"brown",file:"/lpc/feet/feet_shoes_ghillies__brown.png"},{name:"ceramic",file:"/lpc/feet/feet_shoes_ghillies__ceramic.png"},{name:"charcoal",file:"/lpc/feet/feet_shoes_ghillies__charcoal.png"},{name:"copper",file:"/lpc/feet/feet_shoes_ghillies__copper.png"},{name:"forest",file:"/lpc/feet/feet_shoes_ghillies__forest.png"}]},
  {key:"feet_shoes_revised",name:"Revised Shoes",slot:"feet",rarity:"commun",zPos:15,colors:[{name:"black",file:"/lpc/feet/feet_shoes_revised__black.png"},{name:"blue",file:"/lpc/feet/feet_shoes_revised__blue.png"},{name:"bluegray",file:"/lpc/feet/feet_shoes_revised__bluegray.png"},{name:"brass",file:"/lpc/feet/feet_shoes_revised__brass.png"},{name:"bronze",file:"/lpc/feet/feet_shoes_revised__bronze.png"},{name:"brown",file:"/lpc/feet/feet_shoes_revised__brown.png"},{name:"ceramic",file:"/lpc/feet/feet_shoes_revised__ceramic.png"},{name:"charcoal",file:"/lpc/feet/feet_shoes_revised__charcoal.png"},{name:"copper",file:"/lpc/feet/feet_shoes_revised__copper.png"},{name:"forest",file:"/lpc/feet/feet_shoes_revised__forest.png"}]},
  {key:"feet_shoes_sara",name:"Sara Shoes",slot:"feet",rarity:"commun",zPos:15,colors:[{name:"black",file:"/lpc/feet/feet_shoes_sara__black.png"},{name:"blue",file:"/lpc/feet/feet_shoes_sara__blue.png"},{name:"bluegray",file:"/lpc/feet/feet_shoes_sara__bluegray.png"},{name:"brass",file:"/lpc/feet/feet_shoes_sara__brass.png"},{name:"bronze",file:"/lpc/feet/feet_shoes_sara__bronze.png"},{name:"brown",file:"/lpc/feet/feet_shoes_sara__brown.png"},{name:"ceramic",file:"/lpc/feet/feet_shoes_sara__ceramic.png"},{name:"charcoal",file:"/lpc/feet/feet_shoes_sara__charcoal.png"},{name:"copper",file:"/lpc/feet/feet_shoes_sara__copper.png"},{name:"forest",file:"/lpc/feet/feet_shoes_sara__forest.png"}]},
  {key:"hair_afro",name:"Afro",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_afro.png"},
  {key:"hair_balding",name:"Balding",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_balding.png"},
  {key:"hair_bangs_bun",name:"Bangs bun",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_bangs_bun.png"},
  {key:"hair_beards_5oclock_shadow",name:"5 O'clock Shadow",slot:"hair",rarity:"rare",zPos:111,file:"/lpc/hair/hair_beards_5oclock_shadow.png"},
  {key:"hair_beards_beard",name:"Basic Beard",slot:"hair",rarity:"rare",zPos:110,file:"/lpc/hair/hair_beards_beard.png"},
  {key:"hair_beards_medium",name:"Medium Beard",slot:"hair",rarity:"rare",zPos:110,file:"/lpc/hair/hair_beards_medium.png"},
  {key:"hair_beards_trimmed",name:"Trimmed Beard",slot:"hair",rarity:"rare",zPos:110,file:"/lpc/hair/hair_beards_trimmed.png"},
  {key:"hair_beards_winter",name:"Winter Beard",slot:"hair",rarity:"rare",zPos:110,file:"/lpc/hair/hair_beards_winter.png"},
  {key:"hair_bob",name:"Bob",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_bob.png"},
  {key:"hair_bob_side_part",name:"Bob side part",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_bob_side_part.png"},
  {key:"hair_braid",name:"Braid",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_braid.png"},
  {key:"hair_braid2",name:"Braid2",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_braid2.png"},
  {key:"hair_buzzcut",name:"Buzzcut",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_buzzcut.png"},
  {key:"hair_cornrows",name:"Cornrows",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_cornrows.png"},
  {key:"hair_dreadlocks_long",name:"Dreadlocks long",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_dreadlocks_long.png"},
  {key:"hair_dreadlocks_short",name:"Dreadlocks short",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_dreadlocks_short.png"},
  {key:"hair_flat_top_fade",name:"Flat top fade",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_flat_top_fade.png"},
  {key:"hair_flat_top_straight",name:"Flat top straight",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_flat_top_straight.png"},
  {key:"hair_half_up",name:"Half up",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_half_up.png"},
  {key:"hair_high_and_tight",name:"High and tight",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_high_and_tight.png"},
  {key:"hair_high_ponytail",name:"High ponytail",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_high_ponytail.png"},
  {key:"hair_lob",name:"Lob",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_lob.png"},
  {key:"hair_long_tied",name:"Long tied",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_long_tied.png"},
  {key:"hair_longhawk",name:"Longhawk",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_longhawk.png"},
  {key:"hair_natural",name:"Natural",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_natural.png"},
  {key:"hair_ponytail",name:"Ponytail",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_ponytail.png"},
  {key:"hair_ponytail2",name:"Ponytail2",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_ponytail2.png"},
  {key:"hair_relm_ponytail",name:"Relm w/Ponytail",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_relm_ponytail.png"},
  {key:"hair_relm_short",name:"Relm Short",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_relm_short.png"},
  {key:"hair_shorthawk",name:"Shorthawk",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_shorthawk.png"},
  {key:"hair_twists_fade",name:"Twists fade",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_twists_fade.png"},
  {key:"hair_twists_straight",name:"Twists straight",slot:"hair",rarity:"commun",zPos:120,file:"/lpc/hair/hair_twists_straight.png"},
  {key:"headwear_hat_helmet_armet",name:"Armet",slot:"headwear",rarity:"epique",zPos:130,file:"/lpc/headwear/headwear_hat_helmet_armet.png"},
  {key:"headwear_hat_helmet_armet_simple",name:"Simple Armet",slot:"headwear",rarity:"epique",zPos:130,file:"/lpc/headwear/headwear_hat_helmet_armet_simple.png"},
  {key:"headwear_hat_helmet_barbarian",name:"Barbarian",slot:"headwear",rarity:"epique",zPos:130,file:"/lpc/headwear/headwear_hat_helmet_barbarian.png"},
  {key:"headwear_hat_helmet_barbarian_nasal",name:"Barbarian nasal",slot:"headwear",rarity:"epique",zPos:130,file:"/lpc/headwear/headwear_hat_helmet_barbarian_nasal.png"},
  {key:"headwear_hat_helmet_barbarian_viking",name:"Barbarian Viking",slot:"headwear",rarity:"legendaire",zPos:130,file:"/lpc/headwear/headwear_hat_helmet_barbarian_viking.png"},
  {key:"headwear_hat_helmet_barbuta",name:"Barbuta",slot:"headwear",rarity:"epique",zPos:130,file:"/lpc/headwear/headwear_hat_helmet_barbuta.png"},
  {key:"headwear_hat_helmet_barbuta_simple",name:"Simple barbuta",slot:"headwear",rarity:"epique",zPos:130,file:"/lpc/headwear/headwear_hat_helmet_barbuta_simple.png"},
  {key:"headwear_hat_helmet_bascinet",name:"Bascinet",slot:"headwear",rarity:"epique",zPos:130,file:"/lpc/headwear/headwear_hat_helmet_bascinet.png"},
  {key:"headwear_hat_helmet_bascinet_round",name:"Round bascinet",slot:"headwear",rarity:"epique",zPos:130,file:"/lpc/headwear/headwear_hat_helmet_bascinet_round.png"},
  {key:"headwear_hat_helmet_close",name:"Close helm",slot:"headwear",rarity:"epique",zPos:130,file:"/lpc/headwear/headwear_hat_helmet_close.png"},
  {key:"headwear_hat_helmet_flattop",name:"Flattop",slot:"headwear",rarity:"epique",zPos:130,file:"/lpc/headwear/headwear_hat_helmet_flattop.png"},
  {key:"headwear_hat_helmet_greathelm",name:"Greathelm",slot:"headwear",rarity:"epique",zPos:130,file:"/lpc/headwear/headwear_hat_helmet_greathelm.png"},
  {key:"headwear_hat_helmet_horned",name:"Horned helmet",slot:"headwear",rarity:"epique",zPos:130,file:"/lpc/headwear/headwear_hat_helmet_horned.png"},
  {key:"headwear_hat_helmet_kettle",name:"Kettle helm",slot:"headwear",rarity:"epique",zPos:135,file:"/lpc/headwear/headwear_hat_helmet_kettle.png"},
  {key:"headwear_hat_helmet_legion",name:"Legion",slot:"headwear",rarity:"legendaire",zPos:130,file:"/lpc/headwear/headwear_hat_helmet_legion.png"},
  {key:"headwear_hat_helmet_mail",name:"Mail",slot:"headwear",rarity:"epique",zPos:125,file:"/lpc/headwear/headwear_hat_helmet_mail.png"},
  {key:"headwear_hat_helmet_maximus",name:"Maximus",slot:"headwear",rarity:"epique",zPos:130,file:"/lpc/headwear/headwear_hat_helmet_maximus.png"},
  {key:"headwear_hat_helmet_morion",name:"Morion",slot:"headwear",rarity:"epique",zPos:135,file:"/lpc/headwear/headwear_hat_helmet_morion.png"},
  {key:"legs_cuffed",name:"Cuffed Pants",slot:"legs",rarity:"commun",zPos:20,colors:[{name:"black",file:"/lpc/legs/legs_cuffed__black.png"},{name:"blue",file:"/lpc/legs/legs_cuffed__blue.png"},{name:"bluegray",file:"/lpc/legs/legs_cuffed__bluegray.png"},{name:"brown",file:"/lpc/legs/legs_cuffed__brown.png"},{name:"charcoal",file:"/lpc/legs/legs_cuffed__charcoal.png"},{name:"forest",file:"/lpc/legs/legs_cuffed__forest.png"},{name:"gray",file:"/lpc/legs/legs_cuffed__gray.png"},{name:"green",file:"/lpc/legs/legs_cuffed__green.png"},{name:"lavender",file:"/lpc/legs/legs_cuffed__lavender.png"},{name:"leather",file:"/lpc/legs/legs_cuffed__leather.png"}]},
  {key:"legs_formal",name:"Formal Pants",slot:"legs",rarity:"rare",zPos:20,colors:[{name:"base",file:"/lpc/legs/legs_formal__base.png"},{name:"black",file:"/lpc/legs/legs_formal__black.png"},{name:"blue",file:"/lpc/legs/legs_formal__blue.png"},{name:"bluegray",file:"/lpc/legs/legs_formal__bluegray.png"},{name:"brown",file:"/lpc/legs/legs_formal__brown.png"},{name:"charcoal",file:"/lpc/legs/legs_formal__charcoal.png"},{name:"forest",file:"/lpc/legs/legs_formal__forest.png"},{name:"gray",file:"/lpc/legs/legs_formal__gray.png"},{name:"green",file:"/lpc/legs/legs_formal__green.png"},{name:"lavender",file:"/lpc/legs/legs_formal__lavender.png"}]},
  {key:"legs_formal_striped",name:"Striped Formal Pants",slot:"legs",rarity:"rare",zPos:20,colors:[{name:"base",file:"/lpc/legs/legs_formal_striped__base.png"},{name:"black",file:"/lpc/legs/legs_formal_striped__black.png"},{name:"blue",file:"/lpc/legs/legs_formal_striped__blue.png"},{name:"bluegray",file:"/lpc/legs/legs_formal_striped__bluegray.png"},{name:"brown",file:"/lpc/legs/legs_formal_striped__brown.png"},{name:"charcoal",file:"/lpc/legs/legs_formal_striped__charcoal.png"},{name:"forest",file:"/lpc/legs/legs_formal_striped__forest.png"},{name:"gray",file:"/lpc/legs/legs_formal_striped__gray.png"},{name:"green",file:"/lpc/legs/legs_formal_striped__green.png"},{name:"lavender",file:"/lpc/legs/legs_formal_striped__lavender.png"}]},
  {key:"legs_fur",name:"Fur Pants",slot:"legs",rarity:"rare",zPos:20,colors:[{name:"base",file:"/lpc/legs/legs_fur__base.png"},{name:"black",file:"/lpc/legs/legs_fur__black.png"},{name:"blue",file:"/lpc/legs/legs_fur__blue.png"},{name:"bluegray",file:"/lpc/legs/legs_fur__bluegray.png"},{name:"brown",file:"/lpc/legs/legs_fur__brown.png"},{name:"charcoal",file:"/lpc/legs/legs_fur__charcoal.png"},{name:"forest",file:"/lpc/legs/legs_fur__forest.png"},{name:"fur_black",file:"/lpc/legs/legs_fur__fur_black.png"},{name:"fur_brown",file:"/lpc/legs/legs_fur__fur_brown.png"},{name:"fur_copper",file:"/lpc/legs/legs_fur__fur_copper.png"}]},
  {key:"legs_hose",name:"Hose",slot:"legs",rarity:"commun",zPos:20,colors:[{name:"black",file:"/lpc/legs/legs_hose__black.png"},{name:"blue",file:"/lpc/legs/legs_hose__blue.png"},{name:"bluegray",file:"/lpc/legs/legs_hose__bluegray.png"},{name:"brown",file:"/lpc/legs/legs_hose__brown.png"},{name:"charcoal",file:"/lpc/legs/legs_hose__charcoal.png"},{name:"forest",file:"/lpc/legs/legs_hose__forest.png"},{name:"gray",file:"/lpc/legs/legs_hose__gray.png"},{name:"green",file:"/lpc/legs/legs_hose__green.png"},{name:"lavender",file:"/lpc/legs/legs_hose__lavender.png"},{name:"leather",file:"/lpc/legs/legs_hose__leather.png"}]},
  {key:"legs_leggings",name:"Leggings",slot:"legs",rarity:"commun",zPos:20,colors:[{name:"black",file:"/lpc/legs/legs_leggings__black.png"},{name:"blue",file:"/lpc/legs/legs_leggings__blue.png"},{name:"bluegray",file:"/lpc/legs/legs_leggings__bluegray.png"},{name:"brown",file:"/lpc/legs/legs_leggings__brown.png"},{name:"charcoal",file:"/lpc/legs/legs_leggings__charcoal.png"},{name:"forest",file:"/lpc/legs/legs_leggings__forest.png"},{name:"gray",file:"/lpc/legs/legs_leggings__gray.png"},{name:"green",file:"/lpc/legs/legs_leggings__green.png"},{name:"lavender",file:"/lpc/legs/legs_leggings__lavender.png"},{name:"leather",file:"/lpc/legs/legs_leggings__leather.png"}]},
  {key:"legs_leggings2",name:"Leggings 2",slot:"legs",rarity:"commun",zPos:20,colors:[{name:"black",file:"/lpc/legs/legs_leggings2__black.png"},{name:"blue",file:"/lpc/legs/legs_leggings2__blue.png"},{name:"bluegray",file:"/lpc/legs/legs_leggings2__bluegray.png"},{name:"brown",file:"/lpc/legs/legs_leggings2__brown.png"},{name:"charcoal",file:"/lpc/legs/legs_leggings2__charcoal.png"},{name:"forest",file:"/lpc/legs/legs_leggings2__forest.png"},{name:"gray",file:"/lpc/legs/legs_leggings2__gray.png"},{name:"green",file:"/lpc/legs/legs_leggings2__green.png"},{name:"lavender",file:"/lpc/legs/legs_leggings2__lavender.png"},{name:"leather",file:"/lpc/legs/legs_leggings2__leather.png"}]},
  {key:"legs_pantaloons",name:"Pantaloons",slot:"legs",rarity:"commun",zPos:20,colors:[{name:"black",file:"/lpc/legs/legs_pantaloons__black.png"},{name:"blue",file:"/lpc/legs/legs_pantaloons__blue.png"},{name:"bluegray",file:"/lpc/legs/legs_pantaloons__bluegray.png"},{name:"brown",file:"/lpc/legs/legs_pantaloons__brown.png"},{name:"charcoal",file:"/lpc/legs/legs_pantaloons__charcoal.png"},{name:"forest",file:"/lpc/legs/legs_pantaloons__forest.png"},{name:"gray",file:"/lpc/legs/legs_pantaloons__gray.png"},{name:"green",file:"/lpc/legs/legs_pantaloons__green.png"},{name:"lavender",file:"/lpc/legs/legs_pantaloons__lavender.png"},{name:"leather",file:"/lpc/legs/legs_pantaloons__leather.png"}]},
  {key:"legs_pants",name:"Pants",slot:"legs",rarity:"commun",zPos:20,colors:[{name:"black",file:"/lpc/legs/legs_pants__black.png"},{name:"blue",file:"/lpc/legs/legs_pants__blue.png"},{name:"bluegray",file:"/lpc/legs/legs_pants__bluegray.png"},{name:"brown",file:"/lpc/legs/legs_pants__brown.png"},{name:"charcoal",file:"/lpc/legs/legs_pants__charcoal.png"},{name:"forest",file:"/lpc/legs/legs_pants__forest.png"},{name:"gray",file:"/lpc/legs/legs_pants__gray.png"},{name:"green",file:"/lpc/legs/legs_pants__green.png"},{name:"lavender",file:"/lpc/legs/legs_pants__lavender.png"},{name:"leather",file:"/lpc/legs/legs_pants__leather.png"}]},
  {key:"legs_pants2",name:"Long Pants",slot:"legs",rarity:"commun",zPos:20,colors:[{name:"black",file:"/lpc/legs/legs_pants2__black.png"},{name:"blue",file:"/lpc/legs/legs_pants2__blue.png"},{name:"bluegray",file:"/lpc/legs/legs_pants2__bluegray.png"},{name:"brown",file:"/lpc/legs/legs_pants2__brown.png"},{name:"charcoal",file:"/lpc/legs/legs_pants2__charcoal.png"},{name:"forest",file:"/lpc/legs/legs_pants2__forest.png"},{name:"gray",file:"/lpc/legs/legs_pants2__gray.png"},{name:"green",file:"/lpc/legs/legs_pants2__green.png"},{name:"lavender",file:"/lpc/legs/legs_pants2__lavender.png"},{name:"leather",file:"/lpc/legs/legs_pants2__leather.png"}]},
  {key:"legs_shorts",name:"Shorts",slot:"legs",rarity:"commun",zPos:20,colors:[{name:"black",file:"/lpc/legs/legs_shorts__black.png"},{name:"blue",file:"/lpc/legs/legs_shorts__blue.png"},{name:"bluegray",file:"/lpc/legs/legs_shorts__bluegray.png"},{name:"brown",file:"/lpc/legs/legs_shorts__brown.png"},{name:"charcoal",file:"/lpc/legs/legs_shorts__charcoal.png"},{name:"forest",file:"/lpc/legs/legs_shorts__forest.png"},{name:"gray",file:"/lpc/legs/legs_shorts__gray.png"},{name:"green",file:"/lpc/legs/legs_shorts__green.png"},{name:"lavender",file:"/lpc/legs/legs_shorts__lavender.png"},{name:"leather",file:"/lpc/legs/legs_shorts__leather.png"}]},
  {key:"legs_shorts_short",name:"Short Shorts",slot:"legs",rarity:"commun",zPos:20,colors:[{name:"black",file:"/lpc/legs/legs_shorts_short__black.png"},{name:"blue",file:"/lpc/legs/legs_shorts_short__blue.png"},{name:"bluegray",file:"/lpc/legs/legs_shorts_short__bluegray.png"},{name:"brown",file:"/lpc/legs/legs_shorts_short__brown.png"},{name:"charcoal",file:"/lpc/legs/legs_shorts_short__charcoal.png"},{name:"forest",file:"/lpc/legs/legs_shorts_short__forest.png"},{name:"gray",file:"/lpc/legs/legs_shorts_short__gray.png"},{name:"green",file:"/lpc/legs/legs_shorts_short__green.png"},{name:"lavender",file:"/lpc/legs/legs_shorts_short__lavender.png"},{name:"leather",file:"/lpc/legs/legs_shorts_short__leather.png"}]},
  {key:"legs_skirts_legion",name:"Legion skirt",slot:"legs",rarity:"legendaire",zPos:20,file:"/lpc/legs/legs_skirts_legion.png"},
  {key:"legs_skirts_plain",name:"Plain skirt",slot:"legs",rarity:"commun",zPos:20,file:"/lpc/legs/legs_skirts_plain.png"},
  {key:"legs_skirts_slit",name:"Slit skirt",slot:"legs",rarity:"commun",zPos:20,file:"/lpc/legs/legs_skirts_slit.png"},
  {key:"legs_widepants",name:"Wide pants",slot:"legs",rarity:"commun",zPos:20,colors:[{name:"black",file:"/lpc/legs/legs_widepants__black.png"},{name:"blue",file:"/lpc/legs/legs_widepants__blue.png"},{name:"bluegray",file:"/lpc/legs/legs_widepants__bluegray.png"},{name:"brown",file:"/lpc/legs/legs_widepants__brown.png"},{name:"charcoal",file:"/lpc/legs/legs_widepants__charcoal.png"},{name:"forest",file:"/lpc/legs/legs_widepants__forest.png"},{name:"gray",file:"/lpc/legs/legs_widepants__gray.png"},{name:"green",file:"/lpc/legs/legs_widepants__green.png"},{name:"lavender",file:"/lpc/legs/legs_widepants__lavender.png"},{name:"leather",file:"/lpc/legs/legs_widepants__leather.png"}]},
  {key:"torso_clothes_longsleeve",name:"Longsleeve",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_longsleeve.png"},
  {key:"torso_clothes_longsleeve2",name:"Longsleeve 2",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_longsleeve2.png"},
  {key:"torso_clothes_longsleeve2_buttoned",name:"Longsleeve 2 Buttoned",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_longsleeve2_buttoned.png"},
  {key:"torso_clothes_longsleeve2_cardigan",name:"Cardigan",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_longsleeve2_cardigan.png"},
  {key:"torso_clothes_longsleeve2_polo",name:"Longsleeve Polo",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_longsleeve2_polo.png"},
  {key:"torso_clothes_longsleeve2_scoop",name:"Longsleeve 2 Scoop",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_longsleeve2_scoop.png"},
  {key:"torso_clothes_longsleeve2_vneck",name:"Longsleeve 2 VNeck",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_longsleeve2_vneck.png"},
  {key:"torso_clothes_longsleeve_scoop",name:"Scoop",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_longsleeve_scoop.png"},
  {key:"torso_clothes_longsleeves",name:"Original Longsleeves Overlay",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_longsleeves.png"},
  {key:"torso_clothes_longsleeves2",name:"Longsleeves 2 Overlay",slot:"torso",rarity:"commun",zPos:36,file:"/lpc/torso/torso_clothes_longsleeves2.png"},
  {key:"torso_clothes_longsleeves_cuffed",name:"Cuffed Longsleeves Overlay",slot:"torso",rarity:"commun",zPos:36,file:"/lpc/torso/torso_clothes_longsleeves_cuffed.png"},
  {key:"torso_clothes_shortsleeve",name:"Shortsleeve",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_shortsleeve.png"},
  {key:"torso_clothes_shortsleeve_cardigan",name:"Shortsleeve Cardigan",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_shortsleeve_cardigan.png"},
  {key:"torso_clothes_shortsleeve_polo",name:"Shortsleeve Polo",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_shortsleeve_polo.png"},
  {key:"torso_clothes_shortsleeves",name:"Original Shortsleeves Overlay",slot:"torso",rarity:"commun",zPos:36,file:"/lpc/torso/torso_clothes_shortsleeves.png"},
  {key:"torso_clothes_sleeveless1",name:"Original Sleeveless",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_sleeveless1.png"},
  {key:"torso_clothes_sleeveless2",name:"Sleeveless 2",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_sleeveless2.png"},
  {key:"torso_clothes_sleeveless2_buttoned",name:"Sleeveless 2 Buttoned",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_sleeveless2_buttoned.png"},
  {key:"torso_clothes_sleeveless2_cardigan",name:"Sleeveless 2 Cardigan",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_sleeveless2_cardigan.png"},
  {key:"torso_clothes_sleeveless2_polo",name:"Sleeveless 2 Polo",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_sleeveless2_polo.png"},
  {key:"torso_clothes_sleeveless2_scoop",name:"Sleeveless 2 Scoop",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_sleeveless2_scoop.png"},
  {key:"torso_clothes_sleeveless2_vneck",name:"Sleeveless 2 VNeck",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_sleeveless2_vneck.png"},
  {key:"torso_clothes_tshirt",name:"TShirt",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_tshirt.png"},
  {key:"torso_clothes_tshirt_buttoned",name:"TShirt Buttoned",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_tshirt_buttoned.png"},
  {key:"torso_clothes_tshirt_scoop",name:"TShirt Scoop",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_tshirt_scoop.png"},
  {key:"torso_clothes_tshirt_vneck",name:"TShirt VNeck",slot:"torso",rarity:"commun",zPos:35,file:"/lpc/torso/torso_clothes_tshirt_vneck.png"}
];
export const ALL_LAYERS: LpcItem[] = [...BASE_LAYERS, ...ITEMS];
export const ITEM_BY_KEY: Record<string, LpcItem> = Object.fromEntries(ALL_LAYERS.map((i)=>[i.key,i]));
export type EquipSel = { key: string; color?: string };
export type Equipped = Partial<Record<Slot, EquipSel | null>>;
export const DEFAULT_EQUIPPED: Equipped = {"hair": {"key": "hair_afro"}, "torso": {"key": "torso_clothes_longsleeve"}, "legs": {"key": "legs_cuffed"}, "feet": {"key": "feet_shoes_basic"}};
export const STARTER_ITEMS: string[] = ["feet_shoes_basic", "feet_shoes_ghillies", "feet_shoes_revised", "feet_shoes_sara", "hair_afro", "hair_balding", "hair_bangs_bun", "hair_bob", "hair_bob_side_part", "hair_braid", "hair_braid2", "hair_buzzcut", "hair_cornrows", "hair_dreadlocks_long", "hair_dreadlocks_short", "hair_flat_top_fade", "hair_flat_top_straight", "hair_half_up", "hair_high_and_tight", "hair_high_ponytail", "hair_lob", "hair_long_tied", "hair_longhawk", "hair_natural", "hair_ponytail", "hair_ponytail2", "hair_relm_ponytail", "hair_relm_short", "hair_shorthawk", "hair_twists_fade", "hair_twists_straight", "legs_cuffed", "legs_hose", "legs_leggings", "legs_leggings2", "legs_pantaloons", "legs_pants", "legs_pants2", "legs_shorts", "legs_shorts_short", "legs_skirts_plain", "legs_skirts_slit", "legs_widepants", "torso_clothes_longsleeve", "torso_clothes_longsleeve2", "torso_clothes_longsleeve2_buttoned", "torso_clothes_longsleeve2_cardigan", "torso_clothes_longsleeve2_polo", "torso_clothes_longsleeve2_scoop", "torso_clothes_longsleeve2_vneck", "torso_clothes_longsleeve_scoop", "torso_clothes_longsleeves", "torso_clothes_longsleeves2", "torso_clothes_longsleeves_cuffed", "torso_clothes_shortsleeve", "torso_clothes_shortsleeve_cardigan", "torso_clothes_shortsleeve_polo", "torso_clothes_shortsleeves", "torso_clothes_sleeveless1", "torso_clothes_sleeveless2", "torso_clothes_sleeveless2_buttoned", "torso_clothes_sleeveless2_cardigan", "torso_clothes_sleeveless2_polo", "torso_clothes_sleeveless2_scoop", "torso_clothes_sleeveless2_vneck", "torso_clothes_tshirt", "torso_clothes_tshirt_buttoned", "torso_clothes_tshirt_scoop", "torso_clothes_tshirt_vneck"];
export function fileFor(item: LpcItem, color?: string | null): string | null {
  if (item.file) return item.file;
  if (item.colors && item.colors.length) {
    if (color) { const f = item.colors.find((c)=>c.name===color); if (f) return f.file; }
    return item.colors[0].file;
  }
  return null;
}
